server:
  port: 5756
#

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 3
  cloud:
    gateway:
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

dubbo:
  application:
    name: api-gateway
  protocol:
    name: dubbo
    port: 9566
  registry:
    id: nacos
    address: nacos://127.0.0.1:8848