server:
  port: 7000
#

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
      database: 3
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: https://api.52vmy.cn
          predicates:
            - Path=/**
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

dubbo:
  application:
    name: api-gateway
  protocol:
    name: dubbo
    port: 9566
  registry:
    id: nacos
    address: nacos://localhost:8848