server:
  port: 7000
#
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: https://api.52vmy.cn
          predicates:
            - Path=/**
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace