server:
  port: 5756
#

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 3
      password: 123456

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: error

dubbo:
  application:
    name: api-gateway
  protocol:
    name: dubbo
    port: 9566
  registry:
    id: nacos
    address: nacos://127.0.0.1:8848
