server:
  port: 5758
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fusheng_api?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: fusheng_api
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 3
  mail:
    # 邮件配置信息
    # 163邮箱的SMTP服务器配置
    host: smtp.126.com  # SMTP服务器地址
    port: 465 # 端口号（默认为SMTP的标准端口）
    username: fusheng656@126.com  # 发件人邮箱地址
    password: NHFXOAWVGGQHBLJA  # 发件人邮箱密码

fusheng:
  # 加密秘钥
  encrypt-key: 186cfa4cd57b

dubbo:
  application:
    name: api-backend
  protocol:
    name: dubbo
    port: 9565
  registry:
    id: nacos
    address: nacos://127.0.0.1:8848
