server:
  port: 5758
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fusheng_api?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: fusheng_api
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 3
  mail:
    # 邮件配置信息
    # 163邮箱的SMTP服务器配置
    host: smtp.126.com  # SMTP服务器地址
    port: 465 # 端口号（默认为SMTP的标准端口）
    username: fusheng656@126.com  # 发件人邮箱地址
    password: NHFXOAWVGGQHBLJA  # 发件人邮箱密码

fusheng:
  # 加密秘钥
  encrypt-key: 186cfa4cd57b

dubbo:
  application:
    name: api-backend
  protocol:
    name: dubbo
    port: 9565
  registry:
    id: nacos
    address: nacos://127.0.0.1:8848
# 支付宝相关的配置
alipay:
  serverUrl: "https://openapi-sandbox.dl.alipaydev.com/gateway.do"
  appId: "9021000134662567"
  privateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDq809Jpjaj3HkBo1KmJ0D++bxQ7NfxyrpUmVog8ay2g9CPLFiJZ/lAon7ZUJLbIJF5eBEbDfdUipcETRxBvP6qC11kjLTKmzSkTBit4Los/35EsNNcNmSqrMOWicYA+foB6B3FcOADeFImsBX6wFSKl+uvDE5KCuymci92u3DfNRDLl/zVxaF7Tk8yQoIHKU0wos7aste0IVyCe7bOOqwfVmuvmVHeWZZqEeEOzqTN8Mg7jb6ukpqBpGhgJ+mjJYNXpNnM+AgoYIwVA/TAfAZIdt07KRbnu9toYcxiyzOY/8xuk60MwoTLdjydomuX84fwGNub4Qlz04vkOUiBrFzhAgMBAAECggEBANNElHBikNGJ6Bmr9h7IP27HvCl8v7WBmUmHV/81shuwrfKAauCr6PrQ44WgKV33jDiQ2bjdNyEDOka43AbU3p6jd4h56fwh0hVHBA4efOsHl1BHPNe3ZY//qCSOoMix/7iFM3geRqF4KU72md0P4zV45IpUY3W7Gw+Ur89xP07FHKuTijGRKR61BukVYincra/QVxTIyr+j1tq0d5i+W7fjm0tyB/ALt5l/FUAGAwTcHRnJEBhnZ3kBw+ok1R57rzjzfYsMBkKCfVWW9dacz4eASMi2pxmYK6ESC/XYUBy/zN1Aw3fTmkhQW38g+4J+1eRd8PiugVCqeGo+Ikh3rRECgYEA+990gNd1IlKtvJhVMLD7l3DIL6lh7aBikHWzp0B87Bi0PQv7Lg+JJIfZXWKO+Rl1LcoACQAgHbA7xEV1H43mer4wAJf7j1osbtCg5FEoPQWsrsZQtn0KftYLy9oLEH+xS6lpHN8yfPANouHVAR5zLUFE+mYSyObiUKj13p0tkcUCgYEA7szef02ZyoZBEw4EOQ+Z6w7BThsWinZhCXj9nyrhFA+M6+oB7PoNXPqnNN7+s2LIkBnNgdMGwnpFKLhieIoJh29EpQPbU0rL91EqegB2xujOwkWaBLZngdjUFqDpOTOAcayg1fwJIBWSpKgkuFpYIYBKWXxj6fE1ZMranXwA3G0CgYEA2RKSc+A9IWGkPmADO72sd65JuVn//i42BE6MkN6xS0FXRS2oQuA8z/EM0sD4e5MHPHlVYmxrQWr7d4JtGM7RDoQPFtPliHyswqynnV6ckUrssoxUT5KgkwOikwPOeV+zy4OsBagO+UJiXjjHvPkjRqNz8WI7Wk4ySlXz4PIRrgkCgYB1CYOi8O2HDPWn2R7IuJS/V6P2G+CYTByS//GNqP5XTqfKmA4JjyQthcudZg1+7dNOjNbj4gFWH4b1xii82yqAblA+b/12fRoqRGWFFeUg58kt/d7WoG9qfFK2JHcpycwR6oGJXtU6HFiayq30jJLVGINYCFcPuWBp3eH3fWcOoQKBgQDmmxWZlROGlDcYpeUTxxAws0Df/TSD+lgvAxIfPQ5vlt1MPzsmTTu1qndMFF/KSY+9nW33kuLmfaG2/On7V7t06IkCrdy+F0bX9B6ket/hwvYFSpmNgB2/NcDYEt48lOeK24bITfmHFttfoIO8fbNnYSXKcC28FImUeNNh49dVqA==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1aaPkMfV+iL+K2+XgV+2UBed+/CxlYXNgNEWKdvBQQOgeqliUmDXVAqWRW3EXCGEaM6FGq6SsqiVNS9YRZIMN4hu3r/w+cgf0Di6QF/Idw74Zn8EM9iLOJ/o7t072A7T74y/PCcFhpTgVh5oRiXzFv12heUurgs/ZDgTfbRD0l0ZHyVtRDtwMUKFY899596woN871h0KzHGg/mlwpCdqk3LISSjE+hkJFVh0F4IJjOlRwZgSiC1h7gvHxW7iFg3wzFL5DCtCn5xPHUyY33FO5m0NzGhebAwMolXOJcfzKxBtQl3y77fY83mY6oTCoHEmb2m+BuXKt/wJwbqXITlhDwIDAQAB
  format: "json"
  charset: "UTF-8"
  signType: "RSA2"
  notifyUrl: "http://43.136.38.19:5757/pay/notify/balance"
