server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: fusheng_api
  mail:
    # 邮件配置信息
    # 163邮箱的SMTP服务器配置
    protocol: smtp  # 使用的邮件协议
    default-encoding: UTF-8  # 默认编码格式
    test-connection: true # 启动时是否测试连接
    properties:
      # 邮件客户端属性配置
      mail.smtp.auth: true  # 启用SMTP身份验证
      mail.smtp.starttls.enable: true  # 启用STARTTLS协议
      mail.smtp.starttls.required: true  # 要求使用STARTTLS协议
      mail.smtp.socketFactory.port: 465  # SSL连接使用的端口号
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory  # SSL连接的SocketFactory类
      mail.smtp.socketFactory.fallback: false  # SSL连接失败时不回退到非加密连接
  freemarker:
    cache: false #缓存是否开启
    charset: UTF-8 #编码格式
    suffix: .ftl #模板文件后缀
    template-loader-path: classpath:/templates/ftl/ #模板文件前缀

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_delete # 逻辑删除字段
      logic-delete-value: 1 # 逻辑删除值
      logic-not-delete-value: 0 # 逻辑删除未删除值

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true


dubbo:
  application:
    name: api-backend
  protocol:
    name: dubbo
    port: 9565
  registry:
    id: nacos
    address: nacos://127.0.0.1:8848

